### PR TITLE
Remove z index

### PR DESCRIPTION
**Pull request by bjfletcher**
Remove `z-index` for the section meta title, which I believe to be unnecessary.

image

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Reason for this (I think) was the padding around the title, e.g.

screen shot 2016-06-14 at 17 47 32

Does that still work?

Also, seem to be a couple of unrelated files checked in too

**Comment by bjfletcher** [comment]
@ironsidevsquincy Great, do you by any chance remember whether you saw the padding issue on Chrome? If yes, I don't see the issue with the `z-index` removed.

**Comment by ironsidevsquincy** [comment]
Sorry, bad wording, wasn't a padding issue, just meant the text laid on top of the dotted background, and gave a visual padding on either side

**Comment by ironsidevsquincy** [comment]
Basically if it stills looks like the above image, than this is gtg 👍

**Comment by i-like-robots** [comment]
From Slack:

For reference doing the before/after fancy styles with a single element: https://github.com/Financial-Times/next-stream-page/blob/master/shared/components/stream-filters/_main.scss#L68-L113
(should mean the text doesn't need a background/z-index)

**Pull request merged**
