### PR TITLE
copy frontpage's gutter and border styling

### PR DESCRIPTION
**Pull request by bjfletcher**
the stream app uses the following:

https://github.com/Financial-Times/next-front-page/blob/master/shared/components/_card.scss
https://github.com/Financial-Times/next-front-page/blob/master/shared/components/_section.scss

and so it would make better sense to have them in here for use by both apps

I combined the two files into one.

@ironsidevsquincy mentioned on Slack that we'd need to test that this works ok on myFT page

If this PR looks good to you code wise, I'll do some testing next week.

### CODE REVIEW

**Comment by bjfletcher** [comment]
I've removed some specifics that probably should remain in frontpage.

**Comment by ironsidevsquincy** [comment]
Any `card` related styling should live in https://github.com/Financial-Times/n-card 

Apart from that, 👍

**Comment by bjfletcher** [comment]
@ironsidevsquincy I wondered about that (putting some of it into n-card) too.

I feel that guttering and lining in between cards, is a very n-section specific thing.  I feel also that the guttering/lining should be in one place, rather than separate in two places.  They need the same spacing, colouring, and so on. 

I see that there's some styling done to card in n-section already (see _section.scss) and so I think if we're to move some of the guttering/lining stuff to n-card, then we'd want to move this too.

I hope it's ok to keep all the style in one place, which is here.

**Comment by ironsidevsquincy** [comment]
That's true, but I really don't think it's a good idea to have one component effect the styling of a completely different component. Spacing/colouring can be shared between the two.

I think for now put the card's styling in the card component, and we'll have a think about how best to organise it

**Comment by bjfletcher** [comment]
Finally tested it on myFT, all 3 pages looked good. So, let's go!

**Pull request merged**
