### PR TITLE
add create image config/sizes helpers

### PR DESCRIPTION
**Pull request by bjfletcher**
These are used by both frontpage and stream pages. It makes better sense to put these in here as common helpers.

### CODE REVIEW

**Comment by bjfletcher** [comment]
@ironsidevsquincy @andygnewman

**Comment by ironsidevsquincy** [comment]
Maybe these would be better placed in `n-card`? not sure. also, you'll need to export them through `main.js`

**Comment by bjfletcher** [comment]
Yes, these should be in `n-card`.

**Comment by bjfletcher** [comment]
Actually, just realised, seeing as it's quite specific to the `n-section` configuration layout/format/protocol... I think best place is in here, don't you think?

**Comment by andygnewman** [comment]
@bjfletcher I've been taking a look at this type of image size transform, given we will want to do something similar for stream list, which I was going to avoid n-section for and go straight to o-card for styling.

The difficulty is that some of the settings here are very usage specific (eg. imageWidth).

I was thinking of making the version that you put in `next-stream` more flexible to cope with different use cases and then we could thin about abstracting it out into it's own little helper component.

**Comment by bjfletcher** [comment]
@andygnewman Your proposal sounds really good. I'll close this and hopefully your idea will come into fruition.

**Pull request closed without merging**
